//MODAL DIALOG MUTAION TYPES
export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"
export const MODAL_DATA = "MODAL_DATA"
export const MODAL_VISIBILITY_HIDDEN = "MODAL_VISIBILITY_HIDDEN"
export const MODAL_VISIBILITY_VISIBLE = "MODAL_VISIBILITY_VISIBLE"
//PROGRESS LOADER MUTATION TYPES 
export const SHOW_PROGRESS_LOADER = "SHOW_PROGRESS_LOADER"
export const HIDE_PROGRESS_LOADER = "HIDE_PROGRESS_LOADER"
export const PROGRESS_DATA = "PROGRESS_DATA"
//BOOKINGS MUTATION TYPES
export const  UPDATE_BOOKING = "UPDATE_BOOKING"
export const  ADD_BOOKING = "ADD_BOOKING"
export const  REMOVE_BOOKING = "REMOVE_BOOKING"
export const  SET_BOOKINGS = "SET_BOOKINGS"
//REPORTING MUATION TYPES
export const  SET_REPORT_DATA = "SET_REPORT_DATA"
export const  SET_REPORT_DEFINITIONS = "SET_REPORT_DEFINITIONS"
